
/****** Object:  View [dbo].[VI_RECEBIMENTOS_LEITE]    Script Date: 08/08/2024 11:50:03 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



CREATE             VIEW [dbo].[VI_RECEBIMENTOS_LEITE] AS(
SELECT  VI.RECEBIMENTO,
        VI.DATA_EMISSAO,
        VI.TURNO,
        VI.PESSOA,
        PS.RAZAO_SOCIAL,
        PS.NOME_FANTASIA, 
        PS.CPF_CNPJ,
        PS.SITUACAO,
        VI.MOTORISTA,
        M.RAZAO_SOCIAL AS NOME_MOTORISTA,
        VI.ROTA,
        R.DESCRICAO AS NOME_ROTA,
        VI.PERIODO,
        VI.DATA_EMISSAO AS "DATA_ENTRADA",
        ASS.PESSOA AS ASSOCIACAO,        
        ASS.NOME_FANTASIA AS NOME_ASSOCIACAO,
        PS.NOME_FAZENDA,
        PS.LOGRADOURO,
        PS.NUMERO,
        PS.COMPLEMENTO,
        PS.CEP,
        PS.BAIRRO,
        PS.CIDADE,
        C.DESCRICAO AS "DESC_CIDADE",
        C.UF,
        PS.BANCO,
        PS.AGENCIA+'-'+PS.DIG_AGENCIA AS AGENCIA_DIGITO,
        PS.NUMERO_CONTA+'-'+PS.DIG_CONTA AS NUMERO_CONTA_DIGITO,
        VI.VALOR_FRETE_LITRO*VI.QTD_FINALIDADE AS "VALOR_FRETE",
        VI.FINALIDADE,
        F.DESCRICAO AS "DESC_FINALIDADE",
        VI.CATEGORIA_PRODUTOR,
        CP.DESCRICAO AS "DESC_CATEGORIA_PRODUTOR",        
        VI.ORDEM_RECEBIMENTO,
        VI.PRODUTO,
        PD.DESCRICAO AS "DESC_PRODUTO",
        PD.DESC_ABREVIADA,
        'LT' AS "UNIDADE",
        VI.QTD_FINALIDADE,
        VI.PRECO_UNITARIO,
        VI.VALOR_TOTAL_FINALIDADE,
        PF.PLATAFORMA
FROM VI_RECEBIMENTOS_ITENS VI
   JOIN PRODUTOS PD ON (PD.PRODUTO = VI.PRODUTO) 
   LEFT JOIN PESSOAS PS ON (PS.PESSOA = VI.PESSOA) 
   LEFT JOIN CIDADES C ON C.CIDADE=PS.CIDADE
   LEFT JOIN VI_CARRETEIROS M ON (VI.MOTORISTA = M.PESSOA) 
   LEFT JOIN ROTAS R ON (R.ROTA = VI.ROTA)
   LEFT JOIN PLATAFORMAS PF ON (R.PLATAFORMA = PF.PLATAFORMA)
   LEFT	JOIN VI_ASSOCIACOES ASS ON (ASS.PESSOA = VI.ASSOCIACAO)
   LEFT JOIN FINALIDADES F ON VI.FINALIDADE=F.FINALIDADE
   LEFT JOIN CATEGORIAS_PRODUTORES CP ON CP.CATEGORIA_PRODUTOR=VI.CATEGORIA_PRODUTOR
)


GO


