

SELECT * 
FROM
(
	SELECT 
		RL.PESSOA AS PRODUTOR, 
		RL.RAZAO_SOCIAL AS NOME_PRODUTOR, 
		RL.CPF_CNPJ AS CPF, 
		CASE MONTH(RL.DATA_ENTRADA) 
		  WHEN 1 THEN 'JANEIRO'
		  WHEN 2 THEN 'FEVEREIRO'
		  WHEN 3 THEN 'MARÇO'
		  WHEN 4 THEN 'ABRIL'
		  WHEN 5 THEN 'MAIO'
		  WHEN 6 THEN 'JUNHO'
		  WHEN 7 THEN 'JULHO'
		  WHEN 8 THEN 'AGOSTO'
		  WHEN 9 THEN 'SETEMBRO'
		  WHEN 10 THEN 'OUTUBRO'
		  WHEN 11 THEN 'NOVEMBRO'
		  WHEN 12 THEN 'DEZEMBRO'
		END AS MES, 
		YEAR(RL.DATA_ENTRADA) AS ANO, 
		SUM(VALOR_TOTAL_FINALIDADE) AS VALOR_PAGO
	FROM VI_RECEBIMENTOS_LEITE RL
	GROUP BY RL.PESSOA, RL.RAZAO_SOCIAL, RL.CPF_CNPJ, MONTH(RL.DATA_ENTRADA), YEAR(RL.DATA_ENTRADA)
) EM_LINHA

PIVOT 
	(SUM(VALOR_PAGO) FOR MES IN ([JANEIRO],[FEVEREIRO],[MARÇO],[ABRIL],[MAIO],[JUNHO],[JULHO],[AGOSTO],[SETEMBRO],[OUTUBRO],[NOVEMBRO],[DEZEMBRO])) AS EM_COLUNAS
	WHERE ANO = 2015
	ORDER BY NOME_PRODUTOR


